name: ogm

services:
  backend:
    container_name: ogm-backend
    image: docker-spring-boot-postgres:latest
    restart: always
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ogm
      - SPRING_DATASOURCE_USERNAME=${OGM_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${OGM_DB_PASSWORD}
    ports:
      - "36458:36458"

  db:
    container_name: ogm-db
    image: postgres:16-alpine
    restart: always
    volumes:
      - ogm-db-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${OGM_DB_USER}
      POSTGRES_PASSWORD: ${OGM_DB_PASSWORD}
      POSTGRES_DB: ogm

volumes:
  ogm-db-vol:
    name: ogm-db-vol
